import { useState, useEffect } from 'react';
import { X, Printer, Activity } from 'lucide-react';
import api from '../api/axios';

export default function SessionSummary({ session, messages, severity, diagnosis, onClose }) {
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetch = async () => {
      try {
        const res = await api.get(`/ai/session/${session._id}/summary`);
        setSummary(res.data.summary);
      } catch {
        setSummary('Unable to generate summary at this time.');
      } finally {
        setLoading(false);
      }
    };
    fetch();
  }, [session._id]);

  const handlePrint = () => {
    const win = window.open('', '_blank');
    win.document.write(`
      <html>
        <head>
          <title>MediSense AI — Session Summary</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; color: #1e293b; line-height: 1.7; }
            h1 { color: #1e3a5f; font-size: 20px; margin-bottom: 4px; }
            .meta { font-size: 13px; color: #64748b; margin-bottom: 24px; }
            .section { margin-bottom: 20px; }
            .section-title { font-size: 13px; font-weight: 700; color: #3b82f6; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }
            .badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; }
            .condition { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 0.5px solid #f1f5f9; font-size: 13px; }
            .disclaimer { font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px; margin-top: 24px; }
          </style>
        </head>
        <body>
          <h1>MediSense AI — Session Summary</h1>
          <p class="meta">
            Date: ${new Date().toLocaleDateString()} &nbsp;|&nbsp;
            Mode: ${session.mode === 'full' ? 'Full Assessment' : 'Quick Check'}
            ${severity ? `&nbsp;|&nbsp; Severity: ${severity.level} (${severity.score}/10)` : ''}
          </p>

          ${summary ? `<div class="section"><div class="section-title">Summary</div><p>${summary}</p></div>` : ''}

          ${diagnosis ? `
          <div class="section">
            <div class="section-title">Possible Conditions</div>
            ${diagnosis.conditions?.map(c => `
              <div class="condition"><span>${c.name}</span><span>${c.probability}% probability</span></div>
            `).join('')}
            ${diagnosis.seekCareUrgency ? `<p style="margin-top:10px;font-size:13px;">Care urgency: <strong>${diagnosis.seekCareUrgency.replace('-', ' ')}</strong></p>` : ''}
          </div>
          ` : ''}

          ${diagnosis?.recommendations?.length ? `
          <div class="section">
            <div class="section-title">Recommendations</div>
            <ul>${diagnosis.recommendations.map(r => `<li>${r}</li>`).join('')}</ul>
          </div>
          ` : ''}

          <p class="disclaimer">
            This summary was generated by MediSense AI and is intended for informational purposes only.
            It does not constitute medical advice, diagnosis, or treatment. Always consult a qualified
            healthcare professional for medical concerns.
          </p>
        </body>
      </html>
    `);
    win.document.close();
    win.print();
  };

  const severityColor = { Low: '#22c55e', Moderate: '#f59e0b', High: '#ef4444', Critical: '#7c3aed' };

  return (
    <div className="ss-overlay" onClick={onClose}>
      <div className="ss-modal" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="ss-header">
          <div className="ss-header-left">
            <div className="ss-icon"><Activity size={16} /></div>
            <div>
              <p className="ss-title">Session Summary</p>
              <p className="ss-sub">{new Date().toLocaleDateString()} · {session.mode === 'full' ? 'Full Assessment' : 'Quick Check'}</p>
            </div>
          </div>
          <div className="ss-header-actions">
            <button className="ss-print-btn" onClick={handlePrint} title="Print summary">
              <Printer size={15} />
            </button>
            <button className="ss-close-btn" onClick={onClose}>
              <X size={16} />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="ss-body">
          {/* Severity */}
          {severity && (
            <div className="ss-section">
              <p className="ss-section-title">Severity</p>
              <span
                className="ss-badge"
                style={{ background: severityColor[severity.level] + '20', color: severityColor[severity.level] }}
              >
                {severity.level} — {severity.score}/10
              </span>
              {severity.reason && <p className="ss-reason">{severity.reason}</p>}
            </div>
          )}

          {/* AI Summary */}
          <div className="ss-section">
            <p className="ss-section-title">Summary</p>
            {loading ? (
              <div className="ss-loading">Generating summary...</div>
            ) : (
              <p className="ss-summary-text">{summary}</p>
            )}
          </div>

          {/* Diagnosis */}
          {diagnosis && (
            <div className="ss-section">
              <p className="ss-section-title">Possible Conditions</p>
              {diagnosis.conditions?.map((c, i) => (
                <div key={i} className="ss-condition">
                  <div className="ss-condition-top">
                    <span>{c.name}</span>
                    <span>{c.probability}%</span>
                  </div>
                  <div className="ss-bar"><div className="ss-bar-fill" style={{ width: `${c.probability}%` }} /></div>
                </div>
              ))}
              {diagnosis.seekCareUrgency && (
                <p className="ss-urgency">
                  Seek care: <strong>{diagnosis.seekCareUrgency.replace('-', ' ')}</strong>
                </p>
              )}
            </div>
          )}

          {/* Recommendations */}
          {diagnosis?.recommendations?.length > 0 && (
            <div className="ss-section">
              <p className="ss-section-title">Recommendations</p>
              <ul className="ss-recs">
                {diagnosis.recommendations.map((r, i) => (
                  <li key={i}>{r}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Disclaimer */}
          <p className="ss-disclaimer">
            MediSense AI is not a substitute for professional medical advice. Always consult a qualified
            healthcare provider for diagnosis and treatment.
          </p>
        </div>
      </div>

      <style>{`
        .ss-overlay {
          position: fixed; inset: 0;
          background: rgba(0,0,0,0.4);
          z-index: 2000;
          display: flex; align-items: center; justify-content: center;
          padding: 16px;
        }
        .ss-modal {
          background: #fff;
          border-radius: 18px;
          width: 100%; max-width: 500px;
          max-height: 85vh;
          display: flex; flex-direction: column;
          overflow: hidden;
          box-shadow: 0 20px 60px rgba(0,0,0,0.2);
        }
        .ss-header {
          padding: 16px 18px;
          border-bottom: 0.5px solid #e2e8f0;
          display: flex; align-items: center; justify-content: space-between;
        }
        .ss-header-left { display: flex; align-items: center; gap: 10px; }
        .ss-icon {
          width: 34px; height: 34px;
          background: #eff6ff; border-radius: 50%;
          display: flex; align-items: center; justify-content: center;
          color: #3b82f6;
        }
        .ss-title { font-size: 14px; font-weight: 700; color: #1e3a5f; }
        .ss-sub { font-size: 11px; color: #94a3b8; }
        .ss-header-actions { display: flex; gap: 6px; }
        .ss-print-btn, .ss-close-btn {
          background: #f8fafc; border: 0.5px solid #e2e8f0;
          border-radius: 8px; padding: 6px;
          cursor: pointer; display: flex; color: #64748b;
        }
        .ss-print-btn:hover, .ss-close-btn:hover { background: #f1f5f9; }
        .ss-body { overflow-y: auto; padding: 18px; display: flex; flex-direction: column; gap: 18px; }
        .ss-section {}
        .ss-section-title {
          font-size: 11px; font-weight: 700; color: #3b82f6;
          text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px;
        }
        .ss-badge {
          display: inline-block; padding: 4px 12px;
          border-radius: 20px; font-size: 12px; font-weight: 600;
        }
        .ss-reason { font-size: 12px; color: #64748b; margin-top: 6px; }
        .ss-loading { font-size: 13px; color: #94a3b8; font-style: italic; }
        .ss-summary-text { font-size: 13px; color: #475569; line-height: 1.7; white-space: pre-wrap; }
        .ss-condition { margin-bottom: 10px; }
        .ss-condition-top {
          display: flex; justify-content: space-between;
          font-size: 13px; color: #334155; font-weight: 500; margin-bottom: 4px;
        }
        .ss-bar { height: 6px; background: #f1f5f9; border-radius: 3px; overflow: hidden; }
        .ss-bar-fill {
          height: 100%;
          background: linear-gradient(90deg, #3b82f6, #6366f1);
          border-radius: 3px;
        }
        .ss-urgency { font-size: 12px; color: #64748b; margin-top: 8px; }
        .ss-urgency strong { color: #f59e0b; text-transform: capitalize; }
        .ss-recs {
          list-style: none; padding: 0;
          display: flex; flex-direction: column; gap: 5px;
        }
        .ss-recs li { font-size: 13px; color: #475569; padding-left: 12px; position: relative; }
        .ss-recs li::before { content: '–'; position: absolute; left: 0; color: #94a3b8; }
        .ss-disclaimer {
          font-size: 11px; color: #94a3b8; line-height: 1.6;
          border-top: 0.5px solid #f1f5f9; padding-top: 14px;
        }
      `}</style>
    </div>
  );
}