import { useState, useEffect, useRef } from 'react';
import { X, Printer, Activity } from 'lucide-react';
import { useReactToPrint } from 'react-to-print';
import api from '../api/axios';
import { cn } from '@/lib/utils';
import { Dialog, DialogClose, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';

const SEVERITY_CLASSES = {
  Low: { bg: 'bg-severity-low-bg', fg: 'text-severity-low-fg' },
  Moderate: { bg: 'bg-severity-moderate-bg', fg: 'text-severity-moderate-fg' },
  High: { bg: 'bg-severity-high-bg', fg: 'text-severity-high-fg' },
  Critical: { bg: 'bg-severity-critical-bg', fg: 'text-severity-critical-fg' },
};

function PrintableSummary({ ref, session, summary, severity, diagnosis }) {
  return (
    <div ref={ref} className="mx-auto max-w-[700px] p-10 text-neutral-800">
      <h1 className="mb-1 text-xl font-bold text-neutral-900">MediSense AI — Session Summary</h1>
      <p className="mb-6 text-sm text-neutral-500">
        Date: {new Date().toLocaleDateString()} &nbsp;|&nbsp;
        Mode: {session.mode === 'full' ? 'Full Assessment' : 'Quick Check'}
        {severity ? `  |  Severity: ${severity.level} (${severity.score}/10)` : ''}
      </p>

      {summary && (
        <div className="mb-5">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-neutral-500">Summary</p>
          <p className="text-sm leading-relaxed">{summary}</p>
        </div>
      )}

      {diagnosis && (
        <div className="mb-5">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-neutral-500">Possible Conditions</p>
          {diagnosis.conditions?.map((c, i) => (
            <div key={i} className="flex justify-between border-b border-neutral-100 py-1.5 text-sm">
              <span>{c.name}</span>
              <span>{c.probability}% probability</span>
            </div>
          ))}
          {diagnosis.seekCareUrgency && (
            <p className="mt-2 text-sm">
              Care urgency: <strong className="capitalize">{diagnosis.seekCareUrgency.replace('-', ' ')}</strong>
            </p>
          )}
        </div>
      )}

      {diagnosis?.recommendations?.length > 0 && (
        <div className="mb-5">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-neutral-500">Recommendations</p>
          <ul className="list-disc pl-5 text-sm leading-relaxed">
            {diagnosis.recommendations.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        </div>
      )}

      <p className="mt-6 border-t border-neutral-200 pt-4 text-[11px] text-neutral-400">
        This summary was generated by MediSense AI and is intended for informational purposes only. It does not
        constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional for
        medical concerns.
      </p>
    </div>
  );
}

export default function SessionSummary({ session, messages, severity, diagnosis, onClose }) {
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(true);
  const printRef = useRef(null);

  useEffect(() => {
    const fetch = async () => {
      try {
        const res = await api.get(`/ai/session/${session._id}/summary`);
        setSummary(res.data.summary);
      } catch {
        setSummary('Unable to generate summary at this time.');
      } finally {
        setLoading(false);
      }
    };
    fetch();
  }, [session._id]);

  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: 'MediSense AI — Session Summary',
  });

  const sev = severity ? SEVERITY_CLASSES[severity.level] : null;

  return (
    <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent
        showCloseButton={false}
        className="flex max-h-[85vh] flex-col gap-0 overflow-hidden rounded-[18px] p-0 sm:max-w-[500px]"
      >
        <DialogHeader className="flex-row items-center justify-between gap-3 border-b border-border px-[18px] py-4 text-left">
          <div className="flex items-center gap-2.5">
            <div className="flex h-[34px] w-[34px] items-center justify-center rounded-full bg-primary/10 text-primary">
              <Activity size={16} />
            </div>
            <div>
              <DialogTitle className="text-sm font-bold text-foreground">Session Summary</DialogTitle>
              <p className="text-[11px] text-muted-foreground">
                {new Date().toLocaleDateString()} · {session.mode === 'full' ? 'Full Assessment' : 'Quick Check'}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-1.5">
            <button
              onClick={handlePrint}
              title="Print summary"
              className="flex rounded-lg border border-border bg-background p-1.5 text-muted-foreground transition-colors hover:bg-accent"
            >
              <Printer size={15} />
            </button>
            <DialogClose asChild>
              <button className="flex rounded-lg border border-border bg-background p-1.5 text-muted-foreground transition-colors hover:bg-accent">
                <X size={16} />
              </button>
            </DialogClose>
          </div>
        </DialogHeader>

        {/* Body */}
        <div className="flex flex-col gap-[18px] overflow-y-auto p-[18px]">
          {/* Severity */}
          {severity && (
            <div>
              <p className="mb-2 text-[11px] font-bold uppercase tracking-wide text-primary">Severity</p>
              <span className={cn('inline-block rounded-full px-3 py-1 text-xs font-semibold', sev?.bg, sev?.fg)}>
                {severity.level} — {severity.score}/10
              </span>
              {severity.reason && <p className="mt-1.5 text-xs text-muted-foreground">{severity.reason}</p>}
            </div>
          )}

          {/* AI Summary */}
          <div>
            <p className="mb-2 text-[11px] font-bold uppercase tracking-wide text-primary">Summary</p>
            {loading ? (
              <p className="text-[13px] italic text-muted-foreground">Generating summary...</p>
            ) : (
              <p className="whitespace-pre-wrap text-[13px] leading-relaxed text-muted-foreground">{summary}</p>
            )}
          </div>

          {/* Diagnosis */}
          {diagnosis && (
            <div>
              <p className="mb-2 text-[11px] font-bold uppercase tracking-wide text-primary">Possible Conditions</p>
              {diagnosis.conditions?.map((c, i) => (
                <div key={i} className="mb-2.5">
                  <div className="mb-1 flex justify-between text-[13px] font-medium text-foreground">
                    <span>{c.name}</span>
                    <span>{c.probability}%</span>
                  </div>
                  <div className="h-1.5 overflow-hidden rounded-full bg-muted">
                    <div
                      className="h-full rounded-full bg-gradient-to-r from-primary to-primary/60"
                      style={{ width: `${c.probability}%` }}
                    />
                  </div>
                </div>
              ))}
              {diagnosis.seekCareUrgency && (
                <p className="mt-2 text-xs text-muted-foreground">
                  Seek care:{' '}
                  <strong className="capitalize text-severity-moderate-fg">
                    {diagnosis.seekCareUrgency.replace('-', ' ')}
                  </strong>
                </p>
              )}
            </div>
          )}

          {/* Recommendations */}
          {diagnosis?.recommendations?.length > 0 && (
            <div>
              <p className="mb-2 text-[11px] font-bold uppercase tracking-wide text-primary">Recommendations</p>
              <ul className="flex flex-col gap-1.5">
                {diagnosis.recommendations.map((r, i) => (
                  <li key={i} className="relative pl-3 text-[13px] text-muted-foreground">
                    <span className="absolute left-0 text-muted-foreground/70">–</span> {r}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Disclaimer */}
          <p className="border-t border-border/70 pt-3.5 text-[11px] leading-relaxed text-muted-foreground">
            MediSense AI is not a substitute for professional medical advice. Always consult a qualified healthcare
            provider for diagnosis and treatment.
          </p>
        </div>
      </DialogContent>

      {/* Hidden printable version */}
      <div className="hidden">
        <PrintableSummary ref={printRef} session={session} summary={summary} severity={severity} diagnosis={diagnosis} />
      </div>
    </Dialog>
  );
}
