// Offline training script for the symptom classifier — run manually via
// `npm run train-ml` (see package.json) whenever conditionProfiles.js
// changes. Writes backend/ml/model.json, which symptomClassifier.js loads
// at require-time for in-process Node inference (no Python/ONNX/TF.js
// runtime needed in the actual server — this script is dev-time only).
//
// Model: Bernoulli Naive Bayes over binary symptom-present/absent features.
// Chosen specifically for JS-portability: the entire "model" is just two
// small tables of probabilities (a per-condition prior, and a per-condition
// per-symptom probability), and inference is a handful of log-probability
// sums — no matrix libraries, no serialization format beyond plain JSON.
//
// Training data is SYNTHETIC, generated by sampling from conditionProfiles.js's
// hand-curated symptom probabilities (see that file for why a curated
// knowledge base was used instead of an imported public dataset). Each
// synthetic "patient" is a random draw against those probabilities, plus a
// small background noise rate so the classes aren't trivially/perfectly
// separable (a more realistic and honest training signal than a lookup table
// dressed up as ML).
const fs = require('fs');
const path = require('path');
const { SYMPTOM_VOCABULARY, CONDITION_PROFILES } = require('./conditionProfiles');

const RECORDS_PER_CONDITION = 300;
const BACKGROUND_NOISE_RATE = 0.03;
const TEST_SPLIT = 0.2;
const LAPLACE_ALPHA = 1;
const SEED = 42; // fixed seed so training is reproducible run-to-run

// Small deterministic PRNG (mulberry32) — Math.random() isn't seedable, and
// reproducibility matters here (a defense demo re-running training should
// get the same reported accuracy every time).
function mulberry32(seed) {
  let a = seed;
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(SEED);

const conditions = Object.keys(CONDITION_PROFILES);

function generateRecord(condition) {
  const profile = CONDITION_PROFILES[condition];
  const features = {};
  for (const symptom of SYMPTOM_VOCABULARY) {
    const p = profile[symptom] ?? BACKGROUND_NOISE_RATE;
    features[symptom] = rand() < p ? 1 : 0;
  }
  return { condition, features };
}

// Generate and shuffle the full synthetic dataset.
let dataset = [];
for (const condition of conditions) {
  for (let i = 0; i < RECORDS_PER_CONDITION; i++) {
    dataset.push(generateRecord(condition));
  }
}
for (let i = dataset.length - 1; i > 0; i--) {
  const j = Math.floor(rand() * (i + 1));
  [dataset[i], dataset[j]] = [dataset[j], dataset[i]];
}

const splitIndex = Math.floor(dataset.length * (1 - TEST_SPLIT));
const trainSet = dataset.slice(0, splitIndex);
const testSet = dataset.slice(splitIndex);

// ─── Train ───────────────────────────────────────────────────────────────
const priors = {};
const prob1 = {};
const countByCondition = {};

for (const condition of conditions) {
  countByCondition[condition] = 0;
  prob1[condition] = {};
  for (const symptom of SYMPTOM_VOCABULARY) prob1[condition][symptom] = 0;
}

for (const record of trainSet) {
  countByCondition[record.condition] += 1;
  for (const symptom of SYMPTOM_VOCABULARY) {
    if (record.features[symptom] === 1) prob1[record.condition][symptom] += 1;
  }
}

for (const condition of conditions) {
  priors[condition] = countByCondition[condition] / trainSet.length;
  for (const symptom of SYMPTOM_VOCABULARY) {
    // Laplace-smoothed P(symptom=1 | condition).
    prob1[condition][symptom] =
      (prob1[condition][symptom] + LAPLACE_ALPHA) / (countByCondition[condition] + 2 * LAPLACE_ALPHA);
  }
}

// ─── Inference (mirrors symptomClassifier.js exactly, for evaluation) ─────
function predict(features) {
  let best = null;
  let bestScore = -Infinity;
  const scores = {};
  for (const condition of conditions) {
    let logProb = Math.log(priors[condition]);
    for (const symptom of SYMPTOM_VOCABULARY) {
      const p1 = prob1[condition][symptom];
      logProb += features[symptom] === 1 ? Math.log(p1) : Math.log(1 - p1);
    }
    scores[condition] = logProb;
    if (logProb > bestScore) { bestScore = logProb; best = condition; }
  }
  return { best, scores };
}

// ─── Evaluate on held-out test set ─────────────────────────────────────────
let correct = 0;
for (const record of testSet) {
  const { best } = predict(record.features);
  if (best === record.condition) correct += 1;
}
const accuracy = correct / testSet.length;

// ─── Write model.json ───────────────────────────────────────────────────
const model = {
  version: 1,
  trainedAt: new Date().toISOString(),
  vocabulary: SYMPTOM_VOCABULARY,
  conditions,
  priors,
  prob1,
  evaluation: {
    trainSize: trainSet.length,
    testSize: testSet.length,
    accuracy: Math.round(accuracy * 1000) / 1000,
  },
};

fs.writeFileSync(path.join(__dirname, 'model.json'), JSON.stringify(model, null, 2));

console.log(`Trained on ${trainSet.length} synthetic records, evaluated on ${testSet.length} held-out records.`);
console.log(`Held-out accuracy: ${(accuracy * 100).toFixed(1)}% across ${conditions.length} conditions.`);
console.log('Wrote backend/ml/model.json');
