import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  ArrowLeft, Activity, AlertTriangle,
  Phone, Printer, Loader,
} from 'lucide-react';
import { useReactToPrint } from 'react-to-print';
import api from '../api/axios';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';

const SEVERITY_CLASSES = {
  Low: { bg: 'bg-severity-low-bg', fg: 'text-severity-low-fg' },
  Moderate: { bg: 'bg-severity-moderate-bg', fg: 'text-severity-moderate-fg' },
  High: { bg: 'bg-severity-high-bg', fg: 'text-severity-high-fg' },
  Critical: { bg: 'bg-severity-critical-bg', fg: 'text-severity-critical-fg' },
};

function PrintableSession({ ref, session, summary }) {
  if (!session) return null;
  return (
    <div ref={ref} className="mx-auto max-w-[700px] p-10 text-neutral-800">
      <h1 className="mb-1 text-xl font-bold text-neutral-900">MediSense AI — Session Report</h1>
      <p className="mb-6 text-sm text-neutral-500">
        Date: {new Date(session.createdAt).toLocaleDateString()} &nbsp;|&nbsp;
        Mode: {session.mode === 'full' ? 'Full Assessment' : 'Quick Check'} &nbsp;|&nbsp;
        Status: {session.status}
        {session.severityLevel ? `  |  Severity: ${session.severityLevel} (${session.severityScore}/10)` : ''}
      </p>

      {summary && (
        <div className="mb-5">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-neutral-500">Summary</p>
          <p className="text-sm leading-relaxed">{summary}</p>
        </div>
      )}

      {session.symptoms?.length > 0 && (
        <div className="mb-5">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-neutral-500">Symptoms Reported</p>
          <p className="text-sm leading-relaxed">{session.symptoms.map((s) => s.name).join(', ')}</p>
        </div>
      )}

      {session.diagnosis?.conditions?.length > 0 && (
        <div className="mb-5">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-neutral-500">Assessment</p>
          {session.diagnosis.conditions.map((c, i) => (
            <div key={i} className="flex justify-between border-b border-neutral-100 py-1.5 text-sm">
              <span>{c.name}</span>
              <span>{c.probability}%</span>
            </div>
          ))}
          {session.diagnosis.seekCareUrgency && (
            <p className="mt-2 text-sm">
              Care urgency: <strong className="capitalize">{session.diagnosis.seekCareUrgency.replace('-', ' ')}</strong>
            </p>
          )}
        </div>
      )}

      {session.diagnosis?.recommendations?.length > 0 && (
        <div className="mb-5">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-neutral-500">Recommendations</p>
          <ul className="list-disc pl-5 text-sm leading-relaxed">
            {session.diagnosis.recommendations.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        </div>
      )}

      <p className="mt-6 border-t border-neutral-200 pt-4 text-[11px] text-neutral-400">
        This report was generated by MediSense AI for informational purposes only. It does not constitute medical
        advice, diagnosis, or treatment. Always consult a qualified healthcare professional.
      </p>
    </div>
  );
}

export default function SessionDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [session, setSession] = useState(null);
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(true);
  const printRef = useRef(null);

  useEffect(() => {
    const load = async () => {
      try {
        const [sessRes, sumRes] = await Promise.all([
          api.get(`/ai/session/${id}`),
          api.get(`/ai/session/${id}/summary`).catch(() => ({ data: { summary: '' } })),
        ]);
        setSession(sessRes.data.session);
        setSummary(sumRes.data.summary);
      } catch {
        navigate('/history');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [id]);

  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: 'MediSense AI — Session Report',
  });

  if (loading) {
    return (
      <div className="flex h-screen flex-col items-center justify-center gap-3 text-muted-foreground">
        <Loader size={26} className="animate-spin text-primary" />
        <p className="text-[13px]">Loading session...</p>
      </div>
    );
  }

  if (!session) return null;

  const sev = SEVERITY_CLASSES[session.severityLevel];

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="flex items-center gap-3 border-b border-border bg-card px-4 py-3">
        <button
          onClick={() => navigate('/history')}
          className="flex rounded-lg p-1 text-muted-foreground transition-colors hover:bg-accent"
        >
          <ArrowLeft size={18} />
        </button>
        <div className="flex flex-1 items-center gap-2.5">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-primary">
            <Activity size={16} />
          </div>
          <div>
            <p className="font-heading text-sm font-semibold text-foreground">
              {session.mode === 'full' ? 'Full Assessment' : 'Quick Check'}
            </p>
            <p className="text-[11px] text-muted-foreground">
              {new Date(session.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
            </p>
          </div>
        </div>
        <Button variant="outline" size="sm" onClick={handlePrint} className="gap-1.5 rounded-full">
          <Printer size={14} /> Print
        </Button>
      </div>

      <div className="mx-auto flex max-w-[640px] flex-col gap-4 px-4 py-5">
        {/* Emergency banner */}
        {session.emergencyDetected && (
          <div className="flex items-center gap-2.5 rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-[13px] text-destructive">
            <AlertTriangle size={16} />
            <span>Emergency symptoms were detected in this session.</span>
            <a
              href="tel:112"
              className="ml-auto flex items-center gap-1.5 rounded-full bg-destructive px-3 py-1 text-xs text-destructive-foreground no-underline"
            >
              <Phone size={12} /> 112
            </a>
          </div>
        )}

        {/* Meta card */}
        <div className="flex flex-wrap gap-4 rounded-2xl border border-border bg-card p-4">
          {[
            { label: 'Mode', value: session.mode === 'full' ? 'Full Assessment' : 'Quick Check' },
            { label: 'Status', value: session.status.charAt(0).toUpperCase() + session.status.slice(1) },
            { label: 'Messages', value: session.messages?.length || 0 },
            session.severityLevel && {
              label: 'Severity',
              value: `${session.severityLevel} (${session.severityScore}/10)`,
              className: sev?.fg,
            },
            session.ruleBasedTriage?.level === 'Critical' && {
              label: 'Clinical Triage',
              value: session.severityMismatch ? 'Critical (flagged for review)' : 'Critical',
              className: 'text-severity-critical-fg',
            },
          ].filter(Boolean).map((m, i) => (
            <div key={i} className="min-w-[100px]">
              <p className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{m.label}</p>
              <p className={cn('text-[13px] font-semibold text-foreground', m.className)}>{m.value}</p>
            </div>
          ))}
        </div>

        {/* Summary */}
        {summary && (
          <div className="rounded-2xl border border-border bg-card p-4">
            <p className="mb-2.5 text-[11px] font-bold uppercase tracking-wide text-primary">Summary</p>
            <p className="text-[13px] leading-relaxed text-muted-foreground">{summary}</p>
          </div>
        )}

        {/* Symptoms */}
        {session.symptoms?.length > 0 && (
          <div className="rounded-2xl border border-border bg-card p-4">
            <p className="mb-2.5 text-[11px] font-bold uppercase tracking-wide text-primary">Symptoms Reported</p>
            <div className="flex flex-wrap gap-1.5">
              {session.symptoms.map((s, i) => (
                <span key={i} className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
                  {s.name}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Diagnosis */}
        {session.diagnosis?.conditions?.length > 0 && (
          <div className="rounded-2xl border border-border bg-card p-4">
            <p className="mb-3 text-[11px] font-bold uppercase tracking-wide text-primary">Assessment</p>
            {session.diagnosis.conditions.map((c, i) => (
              <div key={i} className="mb-3">
                <div className="mb-1 flex justify-between text-[13px] font-medium text-foreground">
                  <span>{c.name}</span>
                  <span>{c.probability}%</span>
                </div>
                <div className="h-1.5 overflow-hidden rounded-full bg-muted">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-primary to-primary/60"
                    style={{ width: `${c.probability}%` }}
                  />
                </div>
              </div>
            ))}
            {session.diagnosis.seekCareUrgency && (
              <p className="mt-2 text-xs text-muted-foreground">
                Care urgency:{' '}
                <strong className="capitalize text-severity-moderate-fg">
                  {session.diagnosis.seekCareUrgency.replace('-', ' ')}
                </strong>
              </p>
            )}
            {session.diagnosis.recommendations?.length > 0 && (
              <ul className="mt-3 flex flex-col gap-1">
                {session.diagnosis.recommendations.map((r, i) => (
                  <li key={i} className="relative pl-3 text-xs text-muted-foreground">
                    <span className="absolute left-0 text-muted-foreground/70">–</span> {r}
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}

        {/* Conversation */}
        {session.messages?.length > 0 && (
          <div className="rounded-2xl border border-border bg-card p-4">
            <p className="mb-3 text-[11px] font-bold uppercase tracking-wide text-primary">Conversation</p>
            <div className="flex flex-col gap-2">
              {session.messages.map((m, i) => (
                <div key={i} className={cn('flex', m.role === 'user' ? 'justify-end' : 'justify-start')}>
                  <div
                    className={cn(
                      'max-w-[80%] rounded-xl px-3 py-2 text-[13px] leading-relaxed',
                      m.role === 'user'
                        ? 'bg-primary text-primary-foreground'
                        : 'border border-border bg-muted text-foreground'
                    )}
                  >
                    {m.content}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <p className="pb-5 text-center text-[11px] leading-relaxed text-muted-foreground/70">
          MediSense AI is not a substitute for professional medical advice.
        </p>
      </div>

      {/* Hidden printable version */}
      <div className="hidden">
        <PrintableSession ref={printRef} session={session} summary={summary} />
      </div>
    </div>
  );
}
