import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  ArrowLeft, Activity, AlertTriangle,
  Phone, Printer, Loader,
} from 'lucide-react';
import api from '../api/axios';

const severityColor = {
  Low: '#22c55e', Moderate: '#f59e0b',
  High: '#ef4444', Critical: '#7c3aed',
};

export default function SessionDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [session, setSession] = useState(null);
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const [sessRes, sumRes] = await Promise.all([
          api.get(`/ai/session/${id}`),
          api.get(`/ai/session/${id}/summary`).catch(() => ({ data: { summary: '' } })),
        ]);
        setSession(sessRes.data.session);
        setSummary(sumRes.data.summary);
      } catch {
        navigate('/history');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [id]);

  const handlePrint = () => {
    if (!session) return;
    const win = window.open('', '_blank');
    win.document.write(`
      <html><head><title>MediSense AI — Session Report</title>
      <style>
        body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; color: #1e293b; line-height: 1.7; }
        h1 { color: #1e3a5f; font-size: 20px; }
        .meta { font-size: 13px; color: #64748b; margin-bottom: 24px; }
        .section { margin-bottom: 20px; }
        .section-title { font-size: 12px; font-weight: 700; color: #3b82f6; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }
        .msg { padding: 8px 12px; border-radius: 8px; font-size: 13px; margin-bottom: 6px; }
        .msg-user { background: #eff6ff; text-align: right; }
        .msg-ai { background: #f8fafc; border: 1px solid #e2e8f0; }
        .condition { display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 0.5px solid #f1f5f9; font-size: 13px; }
        .disclaimer { font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px; margin-top: 24px; }
      </style></head><body>
      <h1>MediSense AI — Session Report</h1>
      <p class="meta">
        Date: ${new Date(session.createdAt).toLocaleDateString()} &nbsp;|&nbsp;
        Mode: ${session.mode === 'full' ? 'Full Assessment' : 'Quick Check'} &nbsp;|&nbsp;
        Status: ${session.status}
        ${session.severityLevel ? ` &nbsp;|&nbsp; Severity: ${session.severityLevel} (${session.severityScore}/10)` : ''}
      </p>

      ${summary ? `<div class="section"><div class="section-title">Summary</div><p>${summary}</p></div>` : ''}

      ${session.symptoms?.length ? `
        <div class="section">
          <div class="section-title">Symptoms Reported</div>
          <p>${session.symptoms.map(s => s.name).join(', ')}</p>
        </div>` : ''}

      ${session.diagnosis?.conditions?.length ? `
        <div class="section">
          <div class="section-title">Assessment</div>
          ${session.diagnosis.conditions.map(c => `<div class="condition"><span>${c.name}</span><span>${c.probability}%</span></div>`).join('')}
          ${session.diagnosis.seekCareUrgency ? `<p style="margin-top:8px;font-size:13px;">Care urgency: <strong>${session.diagnosis.seekCareUrgency.replace('-', ' ')}</strong></p>` : ''}
        </div>` : ''}

      ${session.diagnosis?.recommendations?.length ? `
        <div class="section">
          <div class="section-title">Recommendations</div>
          <ul>${session.diagnosis.recommendations.map(r => `<li>${r}</li>`).join('')}</ul>
        </div>` : ''}

      <div class="section">
        <div class="section-title">Conversation</div>
        ${session.messages?.map(m => `<div class="msg msg-${m.role === 'user' ? 'user' : 'ai'}"><strong>${m.role === 'user' ? 'You' : 'MediSense AI'}:</strong> ${m.content}</div>`).join('') || ''}
      </div>

      <p class="disclaimer">This report was generated by MediSense AI for informational purposes only. It does not constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional.</p>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  if (loading) return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh', gap: 12, color: '#94a3b8', flexDirection: 'column' }}>
      <Loader size={26} style={{ animation: 'spin 1s linear infinite', color: '#3b82f6' }} />
      <p style={{ fontSize: 13 }}>Loading session...</p>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );

  if (!session) return null;

  const sevColor = severityColor[session.severityLevel];

  return (
    <div style={{ minHeight: '100vh', background: '#f8fafc', fontFamily: 'Inter, sans-serif' }}>
      {/* Header */}
      <div style={{ background: '#fff', borderBottom: '0.5px solid #e2e8f0', padding: '12px 16px', display: 'flex', alignItems: 'center', gap: 12 }}>
        <button onClick={() => navigate('/history')} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#64748b', display: 'flex', padding: 4, borderRadius: 8 }}>
          <ArrowLeft size={18} />
        </button>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, flex: 1 }}>
          <div style={{ width: 32, height: 32, background: '#eff6ff', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#3b82f6' }}>
            <Activity size={16} />
          </div>
          <div>
            <p style={{ fontSize: 14, fontWeight: 600, color: '#1e3a5f' }}>
              {session.mode === 'full' ? 'Full Assessment' : 'Quick Check'}
            </p>
            <p style={{ fontSize: 11, color: '#94a3b8' }}>
              {new Date(session.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}
            </p>
          </div>
        </div>
        <button
          onClick={handlePrint}
          style={{ background: '#f8fafc', border: '0.5px solid #e2e8f0', borderRadius: 8, padding: '6px 12px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#64748b' }}
        >
          <Printer size={14} /> Print
        </button>
      </div>

      <div style={{ maxWidth: 640, margin: '0 auto', padding: '20px 16px', display: 'flex', flexDirection: 'column', gap: 16 }}>

        {/* Emergency banner */}
        {session.emergencyDetected && (
          <div style={{ background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 12, padding: '12px 16px', display: 'flex', alignItems: 'center', gap: 10, color: '#dc2626', fontSize: 13 }}>
            <AlertTriangle size={16} />
            <span>Emergency symptoms were detected in this session.</span>
            <a href="tel:112" style={{ marginLeft: 'auto', background: '#dc2626', color: '#fff', padding: '4px 12px', borderRadius: 20, fontSize: 12, textDecoration: 'none', display: 'flex', alignItems: 'center', gap: 5 }}>
              <Phone size={12} /> 112
            </a>
          </div>
        )}

        {/* Meta card */}
        <div style={{ background: '#fff', border: '0.5px solid #e2e8f0', borderRadius: 14, padding: 16, display: 'flex', gap: 16, flexWrap: 'wrap' }}>
          {[
            { label: 'Mode', value: session.mode === 'full' ? 'Full Assessment' : 'Quick Check' },
            { label: 'Status', value: session.status.charAt(0).toUpperCase() + session.status.slice(1) },
            { label: 'Messages', value: session.messages?.length || 0 },
            session.severityLevel && { label: 'Severity', value: `${session.severityLevel} (${session.severityScore}/10)`, color: sevColor },
          ].filter(Boolean).map((m, i) => (
            <div key={i} style={{ minWidth: 100 }}>
              <p style={{ fontSize: 10, color: '#94a3b8', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 4 }}>{m.label}</p>
              <p style={{ fontSize: 13, fontWeight: 600, color: m.color || '#1e3a5f' }}>{m.value}</p>
            </div>
          ))}
        </div>

        {/* Summary */}
        {summary && (
          <div style={{ background: '#fff', border: '0.5px solid #e2e8f0', borderRadius: 14, padding: 16 }}>
            <p style={{ fontSize: 11, fontWeight: 700, color: '#3b82f6', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 10 }}>Summary</p>
            <p style={{ fontSize: 13, color: '#475569', lineHeight: 1.7 }}>{summary}</p>
          </div>
        )}

        {/* Symptoms */}
        {session.symptoms?.length > 0 && (
          <div style={{ background: '#fff', border: '0.5px solid #e2e8f0', borderRadius: 14, padding: 16 }}>
            <p style={{ fontSize: 11, fontWeight: 700, color: '#3b82f6', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 10 }}>Symptoms Reported</p>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
              {session.symptoms.map((s, i) => (
                <span key={i} style={{ background: '#eff6ff', color: '#1d4ed8', padding: '4px 12px', borderRadius: 20, fontSize: 12, fontWeight: 500 }}>
                  {s.name}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Diagnosis */}
        {session.diagnosis?.conditions?.length > 0 && (
          <div style={{ background: '#fff', border: '0.5px solid #e2e8f0', borderRadius: 14, padding: 16 }}>
            <p style={{ fontSize: 11, fontWeight: 700, color: '#3b82f6', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 12 }}>Assessment</p>
            {session.diagnosis.conditions.map((c, i) => (
              <div key={i} style={{ marginBottom: 12 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, fontWeight: 500, color: '#334155', marginBottom: 4 }}>
                  <span>{c.name}</span><span>{c.probability}%</span>
                </div>
                <div style={{ height: 6, background: '#f1f5f9', borderRadius: 3, overflow: 'hidden' }}>
                  <div style={{ height: '100%', width: `${c.probability}%`, background: 'linear-gradient(90deg, #3b82f6, #6366f1)', borderRadius: 3 }} />
                </div>
              </div>
            ))}
            {session.diagnosis.seekCareUrgency && (
              <p style={{ fontSize: 12, color: '#64748b', marginTop: 8 }}>
                Care urgency: <strong style={{ color: '#f59e0b', textTransform: 'capitalize' }}>{session.diagnosis.seekCareUrgency.replace('-', ' ')}</strong>
              </p>
            )}
            {session.diagnosis.recommendations?.length > 0 && (
              <ul style={{ marginTop: 12, paddingLeft: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 4 }}>
                {session.diagnosis.recommendations.map((r, i) => (
                  <li key={i} style={{ fontSize: 12, color: '#475569', paddingLeft: 12, position: 'relative' }}>
                    <span style={{ position: 'absolute', left: 0, color: '#94a3b8' }}>–</span> {r}
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}

        {/* Conversation */}
        {session.messages?.length > 0 && (
          <div style={{ background: '#fff', border: '0.5px solid #e2e8f0', borderRadius: 14, padding: 16 }}>
            <p style={{ fontSize: 11, fontWeight: 700, color: '#3b82f6', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 12 }}>Conversation</p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {session.messages.map((m, i) => (
                <div key={i} style={{ display: 'flex', justifyContent: m.role === 'user' ? 'flex-end' : 'flex-start' }}>
                  <div style={{
                    maxWidth: '80%', padding: '8px 12px', borderRadius: 12,
                    fontSize: 13, lineHeight: 1.6,
                    background: m.role === 'user' ? '#3b82f6' : '#f8fafc',
                    color: m.role === 'user' ? '#fff' : '#1e293b',
                    border: m.role === 'user' ? 'none' : '0.5px solid #e2e8f0',
                  }}>
                    {m.content}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        <p style={{ fontSize: 11, color: '#cbd5e1', textAlign: 'center', lineHeight: 1.6, paddingBottom: 20 }}>
          MediSense AI is not a substitute for professional medical advice.
        </p>
      </div>
    </div>
  );
}