import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Users, Activity, AlertTriangle, Calendar, Download, Printer, Loader,
} from 'lucide-react';
import toast from 'react-hot-toast';
import { useReactToPrint } from 'react-to-print';
import adminApi from '../../api/adminApi';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';

// Triggers a browser download for a blob fetched through the authenticated
// adminApi instance — a plain <a href> can't carry the Authorization header,
// same reasoning as photoLog.api.js's getPhotoImageUrl.
async function downloadCsv(path, filename) {
  const res = await adminApi.get(path, { responseType: 'blob' });
  const url = URL.createObjectURL(res.data);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function PrintableReport({ ref, stats }) {
  if (!stats) return null;
  return (
    <div ref={ref} className="mx-auto max-w-[700px] p-10 text-neutral-800">
      <h1 className="mb-1 text-xl font-bold text-neutral-900">MediSense AI — Admin Report</h1>
      <p className="mb-6 text-sm text-neutral-500">Generated {new Date().toLocaleString()}</p>

      <div className="mb-5">
        <p className="mb-2 text-xs font-bold uppercase tracking-wide text-neutral-500">Overview</p>
        <div className="grid grid-cols-2 gap-2 text-sm">
          <div className="flex justify-between border-b border-neutral-100 py-1.5">
            <span>Total Users</span><span>{stats.totalUsers}</span>
          </div>
          <div className="flex justify-between border-b border-neutral-100 py-1.5">
            <span>Active Users</span><span>{stats.activeUsers}</span>
          </div>
          <div className="flex justify-between border-b border-neutral-100 py-1.5">
            <span>Total Sessions</span><span>{stats.totalSessions}</span>
          </div>
          <div className="flex justify-between border-b border-neutral-100 py-1.5">
            <span>Completed Sessions</span><span>{stats.completedSessions}</span>
          </div>
          <div className="flex justify-between border-b border-neutral-100 py-1.5">
            <span>Emergency Sessions</span><span>{stats.emergencySessions}</span>
          </div>
          <div className="flex justify-between border-b border-neutral-100 py-1.5">
            <span>Today&apos;s Sessions</span><span>{stats.todaySessions}</span>
          </div>
        </div>
      </div>

      {stats.severityBreakdown?.length > 0 && (
        <div className="mb-5">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-neutral-500">Severity Breakdown</p>
          {stats.severityBreakdown.map((s) => (
            <div key={s._id} className="flex justify-between border-b border-neutral-100 py-1.5 text-sm">
              <span>{s._id}</span>
              <span>{s.count}</span>
            </div>
          ))}
        </div>
      )}

      <p className="mt-6 border-t border-neutral-200 pt-4 text-[11px] text-neutral-400">
        Generated by MediSense AI Admin. For internal operational review only.
      </p>
    </div>
  );
}

export default function AdminReports() {
  const navigate = useNavigate();
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(null);
  const printRef = useRef(null);

  useEffect(() => {
    const load = async () => {
      try {
        const res = await adminApi.get('/admin/stats');
        setStats(res.data);
      } catch {
        navigate('/admin/login');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, []);

  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: 'MediSense AI — Admin Report',
  });

  const handleExport = async (kind) => {
    setExporting(kind);
    try {
      if (kind === 'users') {
        await downloadCsv('/admin/export/users.csv', 'users.csv');
      } else {
        await downloadCsv('/admin/export/sessions.csv', 'sessions.csv');
      }
      toast.success('Export downloaded');
    } catch {
      toast.error('Export failed');
    } finally {
      setExporting(null);
    }
  };

  const statCards = stats ? [
    { label: 'Total Users', value: stats.totalUsers, icon: <Users size={18} />, iconBg: 'bg-primary/10', iconFg: 'text-primary' },
    { label: 'Total Sessions', value: stats.totalSessions, icon: <Activity size={18} />, iconBg: 'bg-secondary/10', iconFg: 'text-secondary' },
    { label: "Today's Sessions", value: stats.todaySessions, icon: <Calendar size={18} />, iconBg: 'bg-severity-low-bg', iconFg: 'text-severity-low-fg' },
    { label: 'Emergencies', value: stats.emergencySessions, icon: <AlertTriangle size={18} />, iconBg: 'bg-severity-high-bg', iconFg: 'text-severity-high-fg' },
  ] : [];

  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto flex max-w-[960px] flex-col gap-4 px-4 py-5">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="font-heading text-xl font-bold text-foreground">Reports</h1>
            <p className="text-sm text-muted-foreground">Export data and print operational summaries</p>
          </div>
          <Button
            variant="outline"
            className="rounded-full"
            onClick={handlePrint}
            disabled={loading || !stats}
          >
            <Printer size={15} /> Print Report
          </Button>
        </div>

        {loading ? (
          <div className="grid grid-cols-2 gap-2.5 sm:grid-cols-4">
            {Array.from({ length: 4 }).map((_, i) => (
              <Skeleton key={i} className="h-[76px] rounded-[14px]" />
            ))}
          </div>
        ) : !stats ? null : (
          <div className="grid grid-cols-2 gap-2.5 sm:grid-cols-4">
            {statCards.map((s, i) => (
              <Card key={i} className="gap-0 rounded-[14px] border-border/70 py-0 shadow-none">
                <CardContent className="flex items-center gap-3 p-4">
                  <div className={`flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-[10px] ${s.iconBg} ${s.iconFg}`}>
                    {s.icon}
                  </div>
                  <div>
                    <p className={`text-2xl font-extrabold leading-none ${s.iconFg}`}>{s.value}</p>
                    <p className="mt-1 text-[11px] text-muted-foreground">{s.label}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {/* Exports */}
        <Card className="rounded-[14px] border-border/70 shadow-none">
          <CardContent className="flex flex-col gap-4 p-5">
            <div className="flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-primary/10 text-primary">
                <Download size={16} />
              </div>
              <p className="text-sm font-bold text-foreground">Export data</p>
            </div>
            <div className="flex flex-wrap gap-2.5">
              <Button
                variant="outline"
                className="rounded-full"
                onClick={() => handleExport('users')}
                disabled={exporting === 'users'}
              >
                {exporting === 'users' ? <Loader size={15} className="animate-spin" /> : <Download size={15} />}
                Export Users CSV
              </Button>
              <Button
                variant="outline"
                className="rounded-full"
                onClick={() => handleExport('sessions')}
                disabled={exporting === 'sessions'}
              >
                {exporting === 'sessions' ? <Loader size={15} className="animate-spin" /> : <Download size={15} />}
                Export Sessions CSV
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Off-screen printable report — react-to-print reads this DOM node directly */}
      <div className="hidden">
        <PrintableReport ref={printRef} stats={stats} />
      </div>
    </div>
  );
}
